import { ReactNode } from "react"

import Navbar from "~/components/Navbar"

import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type Props = {
  children: ReactNode
}

export default function Layout({ children }: Props) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-full h-full grid [grid-template-columns:4rem_1fr]">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
