// This file is generated by icon spritesheet generator

export const iconNames = [
  "Warn",
  "Twitch",
  "Train",
  "Timer",
  "Settings",
  "Search",
  "More",
  "Menu",
  "Logo",
  "Instagram",
  "Info",
  "HowToReg",
  "Home",
  "Help",
  "Face",
  "Diversity",
  "Discord",
  "CursorIdle",
  "ContactSupport",
  "Close",
  "Check",
  "CheckCircle",
  "CaptivePortal",
  "CancelCircle",
  "Calendar",
  "Arrow",
  "Add",
] as const;

export type IconName = (typeof iconNames)[number];
